spring:
  application:
    name: "anodiam-gateway-service"
  cloud:
    gateway:
      default-filters:
        - RewritePath=([^/])$,$1/ # must add trailing slash if not there for compatibility
        - SocialTokenRelay=
      routes:
        - id: anodiam_ui
          uri: http://anodiam-ui.dev-ns.svc.cluster.local
          predicates:
            - Path=/dashboard/**
          filters:
            - RewritePath=/dashboard/(?<segment>.*), /$\{segment}
        - id: anodiam_login
          uri: http://anodiam-login-service.dev-ns.svc.cluster.local
          predicates:
            - Path=/anodiam-login-service/**
          filters:
            - RewritePath=/anodiam-login-service/(?<segment>.*), /$\{segment}
        - id: anodiam_test
          uri: http://localhost:8081
          predicates:
            - Path=/anodiam-test/**
          filters:
            - RewritePath=/anodiam-test/(?<segment>.*), /$\{segment}
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: 740566870787-99ped384lb1lvt6eaqt12iidjp5vqiko.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          facebook:
            provider: facebook
            clientId: 1379541745904838
            clientSecret: ed19df7f580b216dea6897c8c0bb46ed
            scope:
              - email
              - public_profile
        provider:
          facebook:
             userInfoUri: https://graph.facebook.com/me?fields=id,name,email,first_name,middle_name,last_name,picture
    anodiam:
      jwt:
        secret: asdfSFS34wfsdfsdfSDSD32dfsddDDerQSNCK34SOWEK5354fdgdf4
  jpa:
    show-sql: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      "hibernate.default_schema": anodiam
      "hibernate.jdbc.lob.non_contextual_creation": true
  sql:
    init:
      mode: always
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5


logging:
  level:
    root: INFO