spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://postgresql-anodiam.infra-ns.svc.cluster.local:5432/anodiam"
    username: anodiam_user
    password: ${sm://ANODIAM_DB_SECRET}